spring:
  application:
    name: hystrix
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

ribbon:
  MaxAutoRetriesNextServer: 2
  #对连接超时、读取超时都进行重试
  MaxAutoRetries: 1
  #更换实例的次数
  OkToRetryOnAllOperations: true      
 #当前实例重试次数，尝试失败会更换下一个实例 
 
 #为了测试 hystrix 短路功能，我们把 hystrix 等待超时设置得非常小（500毫秒）,此设置一般应大于 ribbon 的重试超时时长，例如 10 秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
 
 
# hystrix 对请求的熔断和断路处理，可以产生监控信息，hystrix dashboard可以实时的进行监控
# actuator 是 spring boot 提供的服务监控工具，提供了各种监控信息的监控端点
# 此配置选项， 可以指定端点名，来暴露监控端点,如果要暴露所有端点，可以用 "*"        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream            